### ISSUE TITLE
NoClassDefFoundError + ClassNotFoundException

### ISSUE THREAD

**Issue by ErythroCraft** [TeamGalacticraft/MachineLib#12]
[crash-2024-10-08_19.23.27-client.txt](https://github.com/user-attachments/files/17297276/crash-2024-10-08_19.23.27-client.txt)

pastebin - https://pastebin.com/wRwemh1H

**Comment by marcus8448** [comment]
Make sure you're using Galacticraft commit [d241854c](https://github.com/TeamGalacticraft/Galacticraft/commit/d241854c23621b0023d59aff94585d34ea3ca036) or later with MachineLib 0.7.0+75 and up.

You can get a pre-built jar from the Galacticraft [actions tab](https://github.com/TeamGalacticraft/Galacticraft/actions/workflows/build.yml).
